# Session 10 - NumPy Core

In [1]:
import numpy as np
import sys 
import time

print(np.__version__)

2.5.3


# TASK 1: Memory Layout & Summation Speed Comparision

In [2]:
# Create a large Python list of integers
numbers_list = list(range(1_000_000))

# Create an equivalent NumPy array
numbers_array = np.array(numbers_list)

# Calculate memory used by Python list
list_memory = sys.getsizeof(numbers_list)

for item in numbers_list:
    list_memory += sys.getsizeof(item)

# Calculate memory used by NumPy array
numpy_memory = numbers_array.nbytes

# Measure Python list summation time
start_time = time.perf_counter()
list_sum = sum(numbers_list)
list_time = time.perf_counter() - start_time

# Measure NumPy array summation time
start_time = time.perf_counter()
numpy_sum = numbers_array.sum()
numpy_time = time.perf_counter() - start_time

print("Python list memory:", list_memory, "bytes")
print("NumPy array memory:", numpy_memory, "bytes")
print("Python list sum:", list_sum)
print("NumPy array sum:", numpy_sum)
print("Time using Python list:", list_time, "seconds")
print("Time using NumPy array:", numpy_time, "seconds")

Python list memory: 36000056 bytes
NumPy array memory: 8000000 bytes
Python list sum: 499999500000
NumPy array sum: 499999500000
Time using Python list: 0.00631610001437366 seconds
Time using NumPy array: 0.008010399993509054 seconds


### Explanation

A Python list stores references to separate Python objects, which creates additional memory overhead. NumPy arrays store numeric values in a contiguous memory block, so they generally use less memory. NumPy also performs vectorized operations using optimized low-level code, which can make operations such as summation faster.

# TASK - 2: Array Creation and Shaping

In [3]:
import numpy as np

# ---------------------------------------
# 1. Convert Python list to NumPy array
# ---------------------------------------
block_ids = list(range(101, 113))  # Creates [101, 102, ..., 112]
city_block_array = np.array(block_ids)

print("City block array:")
print(city_block_array)
print()

# ---------------------------------------
# 2. Create a 3x3 zero matrix and set diagonal
# ---------------------------------------
zero_matrix = np.zeros((3, 3), dtype=int)

# Set diagonal elements to 255
np.fill_diagonal(zero_matrix, 255)

print("3x3 Zero matrix with diagonal 255:")
print(zero_matrix)
print()

# ---------------------------------------
# 3. Generate range of values and reshape
# ---------------------------------------
range_array = np.arange(10, 51, 10)  # 10, 20, 30, 40, 50

# Reshape carefully: number of elements must match rows*cols
# Here we have 5 elements, reshape to 5x1 for safe output
reshaped_array = range_array.reshape(5, 1)

print("Reshaped array from 10–50:")
print(reshaped_array)
print()

# ---------------------------------------
# 4. Interpolate values using linspace
# ---------------------------------------
linspace_array = np.linspace(0, 1, 7)  # 7 values evenly spaced from 0 to 1

print("Linspace array (7 values from 0 to 1):")
print(linspace_array)

City block array:
[101 102 103 104 105 106 107 108 109 110 111 112]

3x3 Zero matrix with diagonal 255:
[[255   0   0]
 [  0 255   0]
 [  0   0 255]]

Reshaped array from 10–50:
[[10]
 [20]
 [30]
 [40]
 [50]]

Linspace array (7 values from 0 to 1):
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


# TASK - 3: Broadcasting Operations

In [4]:
import numpy as np

# -----------------------------
# Step 1: Define base pay and daily bonus
# -----------------------------
base_pay = np.array([
    [100, 100, 100, 100],
    [200, 200, 200, 200],
    [300, 300, 300, 300]
])

daily_bonus = np.array([10, 20, 30, 40])  # 1x4 vector

# -----------------------------
# Step 2: Apply broadcasting
# -----------------------------
# NumPy automatically broadcasts the 1x4 daily_bonus row across all 3 employees
total_pay = base_pay + daily_bonus

# -----------------------------
# Step 3: Display the result
# -----------------------------
print("Total pay matrix after broadcasting addition:")
print(total_pay)

# -----------------------------
# Explanation:
# The daily_bonus array has shape (4,), treated as (1x4).
# When added to base_pay of shape (3x4), NumPy "stretches" daily_bonus
# across the 3 rows, performing element-wise addition automatically.

Total pay matrix after broadcasting addition:
[[110 120 130 140]
 [210 220 230 240]
 [310 320 330 340]]


# TASK - 4: Vectorized Conditional Computation

In [5]:
import numpy as np

# -----------------------------
# Step 1: Define the readings array
# -----------------------------
readings = np.array([-2, -1, 0, 1, 2])

# -----------------------------
# Step 2: Vectorized conditional computation
# If reading >= 0 → square it
# If reading < 0 → cube it
# -----------------------------
result = np.where(readings >= 0, readings**2, readings**3)

# -----------------------------
# Step 3: Display the results
# -----------------------------
print("Original readings:", readings)
print("Transformed results:", result)

# -----------------------------
# Explanation:
# np.where(condition, x, y) checks each element:
# - If condition True, takes value from x
# - If condition False, takes value from y
# Here, readings >= 0 → squared, else cubed.

Original readings: [-2 -1  0  1  2]
Transformed results: [-8 -1  0  1  4]


# TASK - 5: Real Data Loading and Normalization

In [6]:
import numpy as np

try:
    data = np.genfromtxt(r"E:\PYTHON\scores.csv", delimiter=",", skip_header=1, usecols=(1,2,3))
    
    # Calculate means and stds per subject (columns)
    means = data.mean(axis=0)
    stds = data.std(axis=0)
    
    # Normalize
    normalized = (data - means) / stds
    print("Normalized scores:\n", normalized)

except FileNotFoundError:
    print("Error: scores.csv not found in the specified path!")

Error: scores.csv not found in the specified path!
